package ad_create_responsive_search

import (
	"strings"
	"testing"

	. "github.com/onsi/gomega"
)

// Every over-length line must be reported, not just the first: a model that has
// just written fifteen headlines should be able to fix them all in one pass
// rather than discovering them one failed call at a time.
func TestTextAssets_ReportsEveryOverLongLine(t *testing.T) {
	RegisterTestingT(t)

	_, err := textAssets(strings.Join([]string{
		"Short one",
		"This headline is far too long to be accepted",
		"Also fine",
		"Another headline that comfortably exceeds the limit",
	}, "\n"), "headline", minHeadlines, maxHeadlines, maxHeadlineLen)

	Expect(err).ToNot(BeNil())
	Expect(err.Error()).To(ContainSubstring("headline 2"))
	Expect(err.Error()).To(ContainSubstring("headline 4"))
	Expect(err.Error()).To(ContainSubstring("over"))
	// The offending text itself, so the caller does not have to count lines.
	Expect(err.Error()).To(ContainSubstring("This headline is far too long"))
}

// Google counts characters, not bytes. A byte count would reject copy that is
// actually within the limit the moment it contains an em dash or an accent.
func TestTextAssets_CountsCharactersNotBytes(t *testing.T) {
	RegisterTestingT(t)

	// Exactly 30 characters — right on the limit — but more than 30 bytes.
	headline := "Café — naïve piñata déjà vu ok"
	Expect([]rune(headline)).To(HaveLen(maxHeadlineLen))
	Expect(len(headline)).To(BeNumerically(">", 30), "the byte length must exceed the limit for this test to mean anything")

	assets, err := textAssets(headline+"\nSecond one\nThird one", "headline", minHeadlines, maxHeadlines, maxHeadlineLen)
	Expect(err).To(BeNil())
	Expect(assets).To(HaveLen(3))
}

// Copy pasted from a document or generated by a model routinely carries blank
// lines; failing on whitespace would be pedantry rather than protection.
func TestTextAssets_DropsBlankLines(t *testing.T) {
	RegisterTestingT(t)

	assets, err := textAssets("One\n\n  \nTwo\nThree\n", "headline", minHeadlines, maxHeadlines, maxHeadlineLen)
	Expect(err).To(BeNil())
	Expect(assets).To(Equal([]map[string]interface{}{
		{"text": "One"}, {"text": "Two"}, {"text": "Three"},
	}))
}

func TestTextAssets_EnforcesGoogleMinimumsAndMaximums(t *testing.T) {
	RegisterTestingT(t)

	_, err := textAssets("Only\nTwo", "headline", minHeadlines, maxHeadlines, maxHeadlineLen)
	Expect(err).ToNot(BeNil())
	Expect(err.Error()).To(ContainSubstring("at least 3 headlines"))

	var many []string
	for i := 0; i < 20; i++ {
		many = append(many, "Headline")
	}
	_, err = textAssets(strings.Join(many, "\n"), "headline", minHeadlines, maxHeadlines, maxHeadlineLen)
	Expect(err).ToNot(BeNil())
	Expect(err.Error()).To(ContainSubstring("at most 15 headlines"))

	_, err = textAssets("Just one", "description", minDescriptions, maxDescriptions, maxDescLen)
	Expect(err).ToNot(BeNil())
	Expect(err.Error()).To(ContainSubstring("at least 2 descriptions"))
}
