// Code generated by cmd/manifest/manifest.go; DO NOT EDIT.

package actions

import (
	core "flomation.app/automate/executor"

	arithmetic_addition "flomation.app/automate/executor/actions/arithmetic/addition"
	arithmetic_division "flomation.app/automate/executor/actions/arithmetic/division"
	arithmetic_multiplication "flomation.app/automate/executor/actions/arithmetic/multiplication"
	arithmetic_subtraction "flomation.app/automate/executor/actions/arithmetic/subtraction"
	aws_dynamodb "flomation.app/automate/executor/actions/aws/dynamodb"
	aws_ec2_describe "flomation.app/automate/executor/actions/aws/ec2/describe"
	aws_s3_delete "flomation.app/automate/executor/actions/aws/s3/delete"
	aws_s3_get "flomation.app/automate/executor/actions/aws/s3/get"
	aws_s3_list "flomation.app/automate/executor/actions/aws/s3/list"
	aws_s3_put "flomation.app/automate/executor/actions/aws/s3/put"
	common_data_combine "flomation.app/automate/executor/actions/common/data_combine"
	common_data_extract "flomation.app/automate/executor/actions/common/data_extract"
	common_data_rename "flomation.app/automate/executor/actions/common/data_rename"
	common_smtp "flomation.app/automate/executor/actions/common/smtp"
	conditional_if "flomation.app/automate/executor/actions/conditional/if"
	git_add "flomation.app/automate/executor/actions/git/add"
	git_branch "flomation.app/automate/executor/actions/git/branch"
	git_checkout "flomation.app/automate/executor/actions/git/checkout"
	git_clone "flomation.app/automate/executor/actions/git/clone"
	git_commit "flomation.app/automate/executor/actions/git/commit"
	git_pull "flomation.app/automate/executor/actions/git/pull"
	git_push "flomation.app/automate/executor/actions/git/push"
	git_status "flomation.app/automate/executor/actions/git/status"
	git_tag "flomation.app/automate/executor/actions/git/tag"
	nosql_mongodb "flomation.app/automate/executor/actions/nosql/mongodb"
	nosql_redis "flomation.app/automate/executor/actions/nosql/redis"
	output_set "flomation.app/automate/executor/actions/output/set"
	security_antivirus "flomation.app/automate/executor/actions/security/antivirus"
	sql_mysql "flomation.app/automate/executor/actions/sql/mysql"
	sql_oracle "flomation.app/automate/executor/actions/sql/oracle"
	sql_postgresql "flomation.app/automate/executor/actions/sql/postgresql"
	trigger_git_poll "flomation.app/automate/executor/actions/trigger/git_poll"
	trigger_manual "flomation.app/automate/executor/actions/trigger/manual"
)

var Actions = map[string]core.Action{
	"arithmetic/addition":       arithmetic_addition.Execute,
	"arithmetic/division":       arithmetic_division.Execute,
	"arithmetic/multiplication": arithmetic_multiplication.Execute,
	"arithmetic/subtraction":    arithmetic_subtraction.Execute,
	"aws/dynamodb":              aws_dynamodb.Execute,
	"aws/ec2/describe":          aws_ec2_describe.Execute,
	"aws/s3/delete":             aws_s3_delete.Execute,
	"aws/s3/get":                aws_s3_get.Execute,
	"aws/s3/list":               aws_s3_list.Execute,
	"aws/s3/put":                aws_s3_put.Execute,
	"common/data_combine":       common_data_combine.Execute,
	"common/data_extract":       common_data_extract.Execute,
	"common/data_rename":        common_data_rename.Execute,
	"common/smtp":               common_smtp.Execute,
	"conditional/if":            conditional_if.Execute,
	"git/add":                   git_add.Execute,
	"git/branch":                git_branch.Execute,
	"git/checkout":              git_checkout.Execute,
	"git/clone":                 git_clone.Execute,
	"git/commit":                git_commit.Execute,
	"git/pull":                  git_pull.Execute,
	"git/push":                  git_push.Execute,
	"git/status":                git_status.Execute,
	"git/tag":                   git_tag.Execute,
	"nosql/mongodb":             nosql_mongodb.Execute,
	"nosql/redis":               nosql_redis.Execute,
	"output/set":                output_set.Execute,
	"security/antivirus":        security_antivirus.Execute,
	"sql/mysql":                 sql_mysql.Execute,
	"sql/oracle":                sql_oracle.Execute,
	"sql/postgresql":            sql_postgresql.Execute,
	"trigger/git_poll":          trigger_git_poll.Execute,
	"trigger/manual":            trigger_manual.Execute,
}
